# Welcome {.unnumbered}

This is an online resource intended to help people run successful health data science projects in Aotearoa New Zealand. It has been written and collated based on the experience of data science researchers and other contributors. It is aimed at practitioners and those that oversee their work. The guide is intended to provide practical advice and clarifications and link to publicly available resources and references. In describing data science techniques, the guide assumes a basic technical understanding, addressing the context and principles of how these are applied to lead to a successful outcome.

We hope this will be a helpful resource for people and organisations who are starting out in data science, as well as experienced professionals who can share their lessons learned with the wider community in a helpful format.

## About this guide

The guide is structured roughly along a data science [project life cycle](basics.qmd#data-projects-have-a-lifecycle): earlier sections outline the context and setup of a health data science project; later sections introduce the technical aspects of data science including modelling.

This guide, its website form, and its contents are free to use, licensed under the CC [BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License.

Pages are Markdown-formatted text files in a [public GitHub repository](https://github.com/precisiondrivenhealth/guide) published using [Quarto](https://quarto.org/).

## Contributing your mahi

Please contribute your text and ideas to this guide to share your knowledge and questions with the wider health data science community. It is a living document and contributions from all viewpoints are most welcome. 

* You are welcome to send suggestions through email to info at precisiondrivenhealth.com. The more specific you can be, the more quickly your suggestions can be incorporated.

* You can directly contribute clicking the "Edit this page" link in the right sidebar. You'll be prompted to fork the guide's [repository on GitHub](https://github.com/precisiondrivenhealth/guide), edit as desired, and can create a pull request to have your edits reviewed and merged into the guide.

* If you wish to contribute regularly, you can be added as a contributor to the repository.

## Development and ownership of this guide

This guide was originally created through the Precision Driven Health (PDH) partnership between Aotearoa New Zealand’s health information technology (IT) sector, health providers and universities, aimed at improving health outcomes through data science. PDH sought to increase data science capability in New Zealand’s health sector and encourage innovation in the use of health data. The PDH partnership operated from 2016-2023.

Te Whatu Ora hosts this guide on behalf of the NZ health system.

## Contributors and reviewers

Thanks to the following people who have substantially contributed to conceptualising, writing, and/or reviewing this guide.

* Alex Kazemi
* CK Jin
* Duncan Croft
* Edmond Zhang
* Fleur Armstrong
* Ivan Rivera
* Jamal Zolhavarieh
* Juliet Rumball-Smith
* Kelly Atkinson
* Kevin Ross
* Luke Boyle
* Mirza Baig
* Ning Hua
* Pieta Brown
* Quan Sun
* Rachel Owens
* Tom Gutteridge
* Vipula Dissanayake
