---
title: "Introduction"
---

## About this guide

This guide is a collection of learnings based on the experience of Aotearoa New Zealand health data science researchers and other contributors. Aimed at practitioners and those that oversee their work, the guide is intended to provide practical advice without repeating the content of publicly available resources and references; instead, links to these are provided. For data scientists, the guide also assumes a basic understanding of data science techniques, addressing the context and principles of how these are applied to lead to a successful outcome.

Earlier sections outline the context and setup of a health data science project; later sections introduce the technical aspects of data science including modelling.

Please contribute to this guide to share your knowledge and questions with the wider health data science research community.

## About Precision Driven Health

[Precision Driven Health](https://precisiondrivenhealth.com) (PDH) is partnership between Aotearoa New Zealand’s health information technology (IT) sector, health providers and universities, aimed at improving health outcomes through data science.
 
PDH seeks to increase data science capability in New Zealand’s health sector and encourage innovation in the use of health data.

## Contributors and reviewers

We would like to thank the people who contributed to compiling and reviewing this guide:

* Alex Kazemi
* CK Jin
* Duncan Croft
* Edmond Zhang
* Fleur Armstrong
* Ivan Rivera
* Jamal Zolhavarieh
* Juliet Rumball-Smith
* Kelly Atkinson
* Kevin Ross
* Luke Boyle
* Ning Hua
* Pieta Brown
* Quan Sun
* Rachel Owens
* Tom Gutteridge
* Vipula Dissanayake
